services:
  # api-gateway:
  #   build: ./api-gateway
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - user-service
  #     - task-service
  #   networks:
  #     - app-net
  #   environment:
  #     - USER_SERVICE_URL=http://user-service:8081
  #     - TASK_SERVICE_URL=http://task-service:8082

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    networks:
      - app-net
    depends_on:
      - redis
      - db
    env_file: 
    - ./user-service/.env


  # task-service:
  #   build: ./task-service
  #   ports:
  #     - "8082:8082"
  #   networks:
  #     - app-net
  #   depends_on:
  #     - db
  #   env_file: 
  #   - ./task-service/.env


  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:80"
  #   networks:
  #     - app-net

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todo_app
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-net

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-net

volumes:
  db-data:

networks:
  app-net:
    driver: bridge
